version: "3"

services:
  crawl:
    build:
      context: .
      dockerfile: Dockerfile.webtiles
    image: crawl
    container_name: "crawl_webtiles"
    restart: always
    ports:
      - 49491:8080
    volumes:
      - ./data/crawl:/data
